# Generated by Django 3.2.6 on 2021-08-15 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meetingsCount', models.SmallIntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('placeOfBirth', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('handphone', models.CharField(max_length=200)),
                ('education', models.SmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classToAttend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.classdata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.branch')),
                ('classRegistered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.classdata')),
            ],
        ),
    ]
